<?php

namespace Database\Seeders;

use App\Models\City;
use Illuminate\Database\Seeder;

class CitiesSeeder extends Seeder
{
    public function run(): void
    {
        $cities = [
            ['slug' => 'baranovichi',  'name' => 'Барановичи',  'name_in' => 'в Барановичах',  'name_title' => 'Барановичах',  'region' => 'Брестская область'],
            ['slug' => 'brest',        'name' => 'Брест',        'name_in' => 'в Бресте',        'name_title' => 'Бресте',        'region' => 'Брестская область'],
            ['slug' => 'bereza',       'name' => 'Берёза',       'name_in' => 'в Берёзе',        'name_title' => 'Берёзе',        'region' => 'Брестская область'],
            ['slug' => 'beloozersk',   'name' => 'Белоозёрск',   'name_in' => 'в Белоозёрске',   'name_title' => 'Белоозёрске',   'region' => 'Брестская область'],
            ['slug' => 'drogichin',    'name' => 'Дрогичин',     'name_in' => 'в Дрогичине',     'name_title' => 'Дрогичине',     'region' => 'Брестская область'],
            ['slug' => 'zhabinka',     'name' => 'Жабинка',      'name_in' => 'в Жабинке',       'name_title' => 'Жабинке',       'region' => 'Брестская область'],
            ['slug' => 'ivacevichi',   'name' => 'Ивацевичи',    'name_in' => 'в Ивацевичах',    'name_title' => 'Ивацевичах',    'region' => 'Брестская область'],
            ['slug' => 'ivanovo',      'name' => 'Иваново',      'name_in' => 'в Иваново',       'name_title' => 'Иваново',       'region' => 'Брестская область'],
            ['slug' => 'kobrin',       'name' => 'Кобрин',       'name_in' => 'в Кобрине',       'name_title' => 'Кобрине',       'region' => 'Брестская область'],
            ['slug' => 'luninec',      'name' => 'Лунинец',      'name_in' => 'в Лунинце',       'name_title' => 'Лунинце',       'region' => 'Брестская область'],
            ['slug' => 'lyahovichi',   'name' => 'Ляховичи',     'name_in' => 'в Ляховичах',     'name_title' => 'Ляховичах',     'region' => 'Брестская область'],
            ['slug' => 'malorita',     'name' => 'Малорита',     'name_in' => 'в Малорите',      'name_title' => 'Малорите',      'region' => 'Брестская область'],
            ['slug' => 'pinsk',        'name' => 'Пинск',        'name_in' => 'в Пинске',        'name_title' => 'Пинске',        'region' => 'Брестская область'],
            ['slug' => 'pruzhany',     'name' => 'Пружаны',      'name_in' => 'в Пружанах',      'name_title' => 'Пружанах',      'region' => 'Брестская область'],
            ['slug' => 'stolin',       'name' => 'Столин',       'name_in' => 'в Столине',       'name_title' => 'Столине',       'region' => 'Брестская область'],

            ['slug' => 'vitebsk',      'name' => 'Витебск',      'name_in' => 'в Витебске',      'name_title' => 'Витебске',      'region' => 'Витебская область'],
            ['slug' => 'braslav',      'name' => 'Браслав',      'name_in' => 'в Браславе',      'name_title' => 'Браславе',      'region' => 'Витебская область'],
            ['slug' => 'verhnedvinsk', 'name' => 'Верхнедвинск', 'name_in' => 'в Верхнедвинске', 'name_title' => 'Верхнедвинске', 'region' => 'Витебская область'],
            ['slug' => 'glubokoe',     'name' => 'Глубокое',     'name_in' => 'в Глубоком',      'name_title' => 'Глубоком',      'region' => 'Витебская область'],
            ['slug' => 'disna',        'name' => 'Дисна',        'name_in' => 'в Дисне',         'name_title' => 'Дисне',         'region' => 'Витебская область'],
            ['slug' => 'dokshicy',     'name' => 'Докшицы',      'name_in' => 'в Докшицах',      'name_title' => 'Докшицах',      'region' => 'Витебская область'],
            ['slug' => 'dubrovno',     'name' => 'Дубровно',     'name_in' => 'в Дубровно',      'name_title' => 'Дубровно',      'region' => 'Витебская область'],
            ['slug' => 'lepel',        'name' => 'Лепель',       'name_in' => 'в Лепеле',        'name_title' => 'Лепеле',        'region' => 'Витебская область'],
            ['slug' => 'liozno',       'name' => 'Лиозно',       'name_in' => 'в Лиозно',        'name_title' => 'Лиозно',        'region' => 'Витебская область'],
            ['slug' => 'miory',        'name' => 'Миоры',        'name_in' => 'в Миорах',        'name_title' => 'Миорах',        'region' => 'Витебская область'],
            ['slug' => 'novopolock',   'name' => 'Новополоцк',   'name_in' => 'в Новополоцке',   'name_title' => 'Новополоцке',   'region' => 'Витебская область'],
            ['slug' => 'orsha',        'name' => 'Орша',         'name_in' => 'в Орше',          'name_title' => 'Орше',          'region' => 'Витебская область'],
            ['slug' => 'polack',       'name' => 'Полоцк',       'name_in' => 'в Полоцке',       'name_title' => 'Полоцке',       'region' => 'Витебская область'],
            ['slug' => 'postavy',      'name' => 'Поставы',      'name_in' => 'в Поставах',      'name_title' => 'Поставах',      'region' => 'Витебская область'],
            ['slug' => 'rossony',      'name' => 'Россоны',      'name_in' => 'в Россонах',      'name_title' => 'Россонах',      'region' => 'Витебская область'],
            ['slug' => 'senno',        'name' => 'Сенно',        'name_in' => 'в Сенно',         'name_title' => 'Сенно',         'region' => 'Витебская область'],
            ['slug' => 'tolochin',     'name' => 'Толочин',      'name_in' => 'в Толочине',      'name_title' => 'Толочине',      'region' => 'Витебская область'],
            ['slug' => 'ushachi',      'name' => 'Ушачи',        'name_in' => 'в Ушачах',        'name_title' => 'Ушачах',        'region' => 'Витебская область'],
            ['slug' => 'chashniki',    'name' => 'Чашники',      'name_in' => 'в Чашниках',      'name_title' => 'Чашниках',      'region' => 'Витебская область'],
            ['slug' => 'sharkovshina', 'name' => 'Шарковщина',   'name_in' => 'в Шарковщине',    'name_title' => 'Шарковщине',    'region' => 'Витебская область'],
            ['slug' => 'shumilino',    'name' => 'Шумилино',     'name_in' => 'в Шумилино',      'name_title' => 'Шумилино',      'region' => 'Витебская область'],

            ['slug' => 'gomel',        'name' => 'Гомель',       'name_in' => 'в Гомеле',        'name_title' => 'Гомеле',        'region' => 'Гомельская область'],
            ['slug' => 'buda-koshelevo', 'name' => 'Буда-Кошелёво', 'name_in' => 'в Буда-Кошелёво', 'name_title' => 'Буда-Кошелёво', 'region' => 'Гомельская область'],
            ['slug' => 'vetka',        'name' => 'Ветка',        'name_in' => 'в Ветке',         'name_title' => 'Ветке',         'region' => 'Гомельская область'],
            ['slug' => 'dobrush',      'name' => 'Добруш',       'name_in' => 'в Добруше',       'name_title' => 'Добруше',       'region' => 'Гомельская область'],
            ['slug' => 'elsk',         'name' => 'Ельск',        'name_in' => 'в Ельске',        'name_title' => 'Ельске',        'region' => 'Гомельская область'],
            ['slug' => 'zhitkovichi',  'name' => 'Житковичи',    'name_in' => 'в Житковичах',    'name_title' => 'Житковичах',    'region' => 'Гомельская область'],
            ['slug' => 'zhlobin',      'name' => 'Жлобин',       'name_in' => 'в Жлобине',       'name_title' => 'Жлобине',       'region' => 'Гомельская область'],
            ['slug' => 'kalinkovichi', 'name' => 'Калинковичи',  'name_in' => 'в Калинковичах',  'name_title' => 'Калинковичах',  'region' => 'Гомельская область'],
            ['slug' => 'korma',        'name' => 'Корма',        'name_in' => 'в Корме',         'name_title' => 'Корме',         'region' => 'Гомельская область'],
            ['slug' => 'lelchicy',     'name' => 'Лельчицы',     'name_in' => 'в Лельчицах',     'name_title' => 'Лельчицах',     'region' => 'Гомельская область'],
            ['slug' => 'loev',         'name' => 'Лоев',         'name_in' => 'в Лоеве',         'name_title' => 'Лоеве',         'region' => 'Гомельская область'],
            ['slug' => 'mozyr',        'name' => 'Мозырь',       'name_in' => 'в Мозыре',        'name_title' => 'Мозыре',        'region' => 'Гомельская область'],
            ['slug' => 'narovlya',     'name' => 'Наровля',      'name_in' => 'в Наровле',       'name_title' => 'Наровле',       'region' => 'Гомельская область'],
            ['slug' => 'oktyabrsky',   'name' => 'Октябрьский',  'name_in' => 'в Октябрьском',   'name_title' => 'Октябрьском',   'region' => 'Гомельская область'],
            ['slug' => 'petrikov',     'name' => 'Петриков',     'name_in' => 'в Петрикове',     'name_title' => 'Петрикове',     'region' => 'Гомельская область'],
            ['slug' => 'rechica',      'name' => 'Речица',       'name_in' => 'в Речице',        'name_title' => 'Речице',        'region' => 'Гомельская область'],
            ['slug' => 'rogachev',     'name' => 'Рогачёв',      'name_in' => 'в Рогачёве',      'name_title' => 'Рогачёве',      'region' => 'Гомельская область'],
            ['slug' => 'svetlogorsk',  'name' => 'Светлогорск',  'name_in' => 'в Светлогорске',  'name_title' => 'Светлогорске',  'region' => 'Гомельская область'],
            ['slug' => 'chechersk',    'name' => 'Чечерск',      'name_in' => 'в Чечерске',      'name_title' => 'Чечерске',      'region' => 'Гомельская область'],

            ['slug' => 'grodno',       'name' => 'Гродно',       'name_in' => 'в Гродно',        'name_title' => 'Гродно',        'region' => 'Гродненская область'],
            ['slug' => 'berestovica',  'name' => 'Берестовица',  'name_in' => 'в Берестовице',   'name_title' => 'Берестовице',   'region' => 'Гродненская область'],
            ['slug' => 'volkovysk',    'name' => 'Волковыск',    'name_in' => 'в Волковыске',    'name_title' => 'Волковыске',    'region' => 'Гродненская область'],
            ['slug' => 'dyatlovo',     'name' => 'Дятлово',      'name_in' => 'в Дятлово',       'name_title' => 'Дятлово',       'region' => 'Гродненская область'],
            ['slug' => 'zelva',        'name' => 'Зельва',       'name_in' => 'в Зельве',        'name_title' => 'Зельве',        'region' => 'Гродненская область'],
            ['slug' => 'ivye',         'name' => 'Ивье',         'name_in' => 'в Ивье',          'name_title' => 'Ивье',          'region' => 'Гродненская область'],
            ['slug' => 'korelichi',    'name' => 'Кореличи',     'name_in' => 'в Кореличах',     'name_title' => 'Кореличах',     'region' => 'Гродненская область'],
            ['slug' => 'lida',         'name' => 'Лида',         'name_in' => 'в Лиде',          'name_title' => 'Лиде',          'region' => 'Гродненская область'],
            ['slug' => 'mosty',        'name' => 'Мосты',        'name_in' => 'в Мостах',        'name_title' => 'Мостах',        'region' => 'Гродненская область'],
            ['slug' => 'novogrudok',   'name' => 'Новогрудок',   'name_in' => 'в Новогрудке',    'name_title' => 'Новогрудке',    'region' => 'Гродненская область'],
            ['slug' => 'ostrovets',    'name' => 'Островец',     'name_in' => 'в Островце',      'name_title' => 'Островце',      'region' => 'Гродненская область'],
            ['slug' => 'oshnyany',     'name' => 'Ошмяны',       'name_in' => 'в Ошмянах',       'name_title' => 'Ошмянах',       'region' => 'Гродненская область'],
            ['slug' => 'slonim',       'name' => 'Слоним',       'name_in' => 'в Слониме',       'name_title' => 'Слониме',       'region' => 'Гродненская область'],
            ['slug' => 'smorgon',      'name' => 'Сморгонь',     'name_in' => 'в Сморгони',      'name_title' => 'Сморгони',      'region' => 'Гродненская область'],
            ['slug' => 'shchuchin',    'name' => 'Щучин',        'name_in' => 'в Щучине',        'name_title' => 'Щучине',        'region' => 'Гродненская область'],

            ['slug' => 'minsk',        'name' => 'Минск',        'name_in' => 'в Минске',        'name_title' => 'Минске',        'region' => 'Минск'],

            ['slug' => 'molodechno',   'name' => 'Молодечно',    'name_in' => 'в Молодечно',     'name_title' => 'Молодечно',     'region' => 'Минская область'],
            ['slug' => 'berezino',     'name' => 'Березино',     'name_in' => 'в Березино',      'name_title' => 'Березино',      'region' => 'Минская область'],
            ['slug' => 'borisov',      'name' => 'Борисов',      'name_in' => 'в Борисове',      'name_title' => 'Борисове',      'region' => 'Минская область'],
            ['slug' => 'vileyka',      'name' => 'Вилейка',      'name_in' => 'в Вилейке',       'name_title' => 'Вилейке',       'region' => 'Минская область'],
            ['slug' => 'volozhin',     'name' => 'Воложин',      'name_in' => 'в Воложине',      'name_title' => 'Воложине',      'region' => 'Минская область'],
            ['slug' => 'dzerzhinsk',   'name' => 'Дзержинск',    'name_in' => 'в Дзержинске',    'name_title' => 'Дзержинске',    'region' => 'Минская область'],
            ['slug' => 'zhodino',      'name' => 'Жодино',       'name_in' => 'в Жодино',        'name_title' => 'Жодино',        'region' => 'Минская область'],
            ['slug' => 'zaslavl',      'name' => 'Заславль',     'name_in' => 'в Заславле',      'name_title' => 'Заславле',      'region' => 'Минская область'],
            ['slug' => 'kopyl',        'name' => 'Копыль',       'name_in' => 'в Копыле',        'name_title' => 'Копыле',        'region' => 'Минская область'],
            ['slug' => 'krupki',       'name' => 'Крупки',       'name_in' => 'в Крупках',       'name_title' => 'Крупках',       'region' => 'Минская область'],
            ['slug' => 'logojsk',      'name' => 'Логойск',      'name_in' => 'в Логойске',      'name_title' => 'Логойске',      'region' => 'Минская область'],
            ['slug' => 'lyuban',       'name' => 'Любань',       'name_in' => 'в Любани',        'name_title' => 'Любани',        'region' => 'Минская область'],
            ['slug' => 'myadel',       'name' => 'Мядель',       'name_in' => 'в Мяделе',        'name_title' => 'Мяделе',        'region' => 'Минская область'],
            ['slug' => 'nesvizh',      'name' => 'Несвиж',       'name_in' => 'в Несвиже',       'name_title' => 'Несвиже',       'region' => 'Минская область'],
            ['slug' => 'puhovichi',    'name' => 'Пуховичи',     'name_in' => 'в Пуховичах',     'name_title' => 'Пуховичах',     'region' => 'Минская область'],
            ['slug' => 'slutsk',       'name' => 'Слуцк',        'name_in' => 'в Слуцке',        'name_title' => 'Слуцке',        'region' => 'Минская область'],
            ['slug' => 'smolevichi',   'name' => 'Смолевичи',    'name_in' => 'в Смолевичах',    'name_title' => 'Смолевичах',    'region' => 'Минская область'],
            ['slug' => 'soligorsk',    'name' => 'Солигорск',    'name_in' => 'в Солигорске',    'name_title' => 'Солигорске',    'region' => 'Минская область'],
            ['slug' => 'starye-dorogi', 'name' => 'Старые Дороги', 'name_in' => 'в Старых Дорогах', 'name_title' => 'Старых Дорогах', 'region' => 'Минская область'],
            ['slug' => 'stolbcy',      'name' => 'Столбцы',      'name_in' => 'в Столбцах',      'name_title' => 'Столбцах',      'region' => 'Минская область'],
            ['slug' => 'uzda',         'name' => 'Узда',         'name_in' => 'в Узде',          'name_title' => 'Узде',          'region' => 'Минская область'],
            ['slug' => 'cherven',      'name' => 'Червень',      'name_in' => 'в Червене',       'name_title' => 'Червене',       'region' => 'Минская область'],

            ['slug' => 'mogilev',      'name' => 'Могилёв',      'name_in' => 'в Могилёве',      'name_title' => 'Могилёве',      'region' => 'Могилёвская область'],
            ['slug' => 'belynichi',    'name' => 'Белыничи',     'name_in' => 'в Белыничах',     'name_title' => 'Белыничах',     'region' => 'Могилёвская область'],
            ['slug' => 'byhov',        'name' => 'Быхов',        'name_in' => 'в Быхове',        'name_title' => 'Быхове',        'region' => 'Могилёвская область'],
            ['slug' => 'glusk',        'name' => 'Глуск',        'name_in' => 'в Глуске',        'name_title' => 'Глуске',        'region' => 'Могилёвская область'],
            ['slug' => 'gorki',        'name' => 'Горки',        'name_in' => 'в Горках',        'name_title' => 'Горках',        'region' => 'Могилёвская область'],
            ['slug' => 'gorodeya',     'name' => 'Городея',      'name_in' => 'в Городее',       'name_title' => 'Городее',       'region' => 'Могилёвская область'],
            ['slug' => 'dribin',       'name' => 'Дрибин',       'name_in' => 'в Дрибине',       'name_title' => 'Дрибине',       'region' => 'Могилёвская область'],
            ['slug' => 'kirovsk',      'name' => 'Кировск',      'name_in' => 'в Кировске',      'name_title' => 'Кировске',      'region' => 'Могилёвская область'],
            ['slug' => 'klimovichi',   'name' => 'Климовичи',    'name_in' => 'в Климовичах',    'name_title' => 'Климовичах',    'region' => 'Могилёвская область'],
            ['slug' => 'klichev',      'name' => 'Кличев',       'name_in' => 'в Кличеве',       'name_title' => 'Кличеве',       'region' => 'Могилёвская область'],
            ['slug' => 'kostyukovichi', 'name' => 'Костюковичи', 'name_in' => 'в Костюковичах',  'name_title' => 'Костюковичах',  'region' => 'Могилёвская область'],
            ['slug' => 'krasnopoye',   'name' => 'Краснополье',  'name_in' => 'в Краснополье',   'name_title' => 'Краснополье',   'region' => 'Могилёвская область'],
            ['slug' => 'krugloe',      'name' => 'Круглое',      'name_in' => 'в Круглом',       'name_title' => 'Круглом',       'region' => 'Могилёвская область'],
            ['slug' => 'mstislavl',    'name' => 'Мстиславль',   'name_in' => 'в Мстиславле',    'name_title' => 'Мстиславле',    'region' => 'Могилёвская область'],
            ['slug' => 'osipovichi',   'name' => 'Осиповичи',    'name_in' => 'в Осиповичах',    'name_title' => 'Осиповичах',    'region' => 'Могилёвская область'],
            ['slug' => 'slavgorod',    'name' => 'Славгород',    'name_in' => 'в Славгороде',    'name_title' => 'Славгороде',    'region' => 'Могилёвская область'],
            ['slug' => 'hotimsk',      'name' => 'Хотимск',      'name_in' => 'в Хотимске',      'name_title' => 'Хотимске',      'region' => 'Могилёвская область'],
            ['slug' => 'cherikov',     'name' => 'Чериков',      'name_in' => 'в Черикове',      'name_title' => 'Черикове',      'region' => 'Могилёвская область'],
            ['slug' => 'shklov',       'name' => 'Шклов',        'name_in' => 'в Шклове',        'name_title' => 'Шклове',        'region' => 'Могилёвская область'],
        ];

        foreach ($cities as $city) {
            City::updateOrCreate(['slug' => $city['slug']], $city);
        }
    }
}
